### PR TITLE
introduce a hightlightJsVersion variable in the config to control highli...

### PR DESCRIPTION
**Pull request by romain-grecourt**
Had some issue with Java syntax highligths when using generics, see https://hk2.java.net/2.2.0-b24/custom-resolver-example.html.
Figured that version 7.5 fixes the issue.

However only this is hardcoded currently and only one version of the reflow maven skin is published.
This change is about exposing highlightjs's version to configuration in site.xml.

### CODE REVIEW

**Comment by andriusvelykis** [comment]
Thanks for reporting and the changes!

It is unfortunate that I have fallen behind with the versions - the solution does look future-proof in regards to the future releases of highlightJs.

I will merge this soon. I guess then it will become available as the -SNAPSHOT release, but I hoped to get more issues fixed for the next proper release. Would -SNAPSHOTS be enough for now?

**Comment by romain-grecourt** [comment]
I can't use SNAPSHOT as this is hooked into our release process  (SNAPSHOTs are forbidden :( ) .
Would you consider doing a micro release ? such as 1.0.1 ?

**Comment by andriusvelykis** [comment]
I think I will do a small release then. I will also try to bump other library versions and include the local resource option (e.g. #18).

Furthermore, while thinking about solution for #18, I am leaning away from adding additional configuration flags. For convenience, I would try to keep up to date with all the new releases, but the versions would be hard-coded for simplicity.

For any other customisations, there is the [`decoration.head`](http://maven.apache.org/doxia/doxia-sitetools/doxia-decoration-model/decoration.html#body) configuration element. It allows arbitrary HTML and can be used to include your own CSS/JavaScript. It also supports Velocity variables, so provides a solution for such problems. Please see my reply in #18.

What do you think? Would this work for your use case?

**Comment by romain-grecourt** [comment]
I'm fine with #18.
Any ETA regarding the release ?

**Comment by andriusvelykis** [comment]
Sorry - I will try to do the release asap.

**Comment by andriusvelykis** [comment]
Fixed as discussed - see #24.

Closing the pull request.

**Comment by andriusvelykis** [comment]
Done - released 1.1.0 :)

**Comment by romain-grecourt** [comment]
Thanks, trying now !

**Pull request closed without merging**
